A <%=raw @exception.class %> occurred:

  <%=raw @exception.message %>
  <%=raw @backtrace.first %>

<%=raw @sections.map { |section| render_section(section) }.join %>
